# Generated by Django 5.2.5 on 2025-08-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Величина скидки')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум применений')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Сколько раз использовали')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
