# Generated by Django 5.2.5 on 2025-08-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Например: levels, shape, topping, berries, decor', max_length=60, unique=True, verbose_name='Слаг')),
                ('multi_select', models.BooleanField(default=False, verbose_name='Множественный выбор')),
            ],
            options={
                'verbose_name': 'Категория опций',
                'verbose_name_plural': 'Категории опций',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Надбавка к цене')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='catalog.optioncategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'unique_together': {('category', 'name')},
            },
        ),
    ]
