# Generated by Django 5.2.5 on 2025-08-27 18:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название торта')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='cakes/', verbose_name='Главная картинка')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Базовая цена, ₽')),
                ('weight_grams', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес, г')),
                ('servings', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порций')),
                ('diameter_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр, см')),
                ('allow_inscription', models.BooleanField(default=True, verbose_name='Разрешить надпись')),
                ('inscription_extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Доплата за надпись, ₽')),
                ('prep_time_min_hours', models.PositiveSmallIntegerField(default=24, verbose_name='Подготовка, мин. часов')),
                ('prep_time_max_hours', models.PositiveSmallIntegerField(default=48, verbose_name='Подготовка, макс. часов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('available_fillings', models.ManyToManyField(blank=True, limit_choices_to={'category__slug': 'filling'}, related_name='cakes_with_filling', to='catalog.option', verbose_name='Доступные начинки')),
            ],
            options={
                'verbose_name': 'Торт (базовый)',
                'verbose_name_plural': 'Торты (базовые)',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cakes/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=120, verbose_name='Alt-текст')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.cake', verbose_name='Торт')),
            ],
            options={
                'verbose_name': 'Фото торта',
                'verbose_name_plural': 'Фото тортов',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
