# Generated by Django 5.2.5 on 2025-08-26 17:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('paid', 'Оплачен'), ('preparing', 'Готовится'), ('on_delivery', 'Доставляется'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя получателя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=30, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=30, verbose_name='Квартира')),
                ('delivery_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий к доставке')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('consent_personal_data', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
                ('utm_source', models.CharField(blank=True, max_length=80, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=80, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='utm_campaign')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма позиций')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Скидка')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость доставки')),
                ('rush_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Срочность (в 24ч)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итого к оплате')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Клиент')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_text', models.CharField(blank=True, max_length=64, verbose_name='Текст надписи')),
                ('inscription_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Цена надписи')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Базовая цена торта')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма по позиции')),
                ('levels', models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'levels'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_items', to='catalog.option', verbose_name='Уровни')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('shape', models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'shape'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shape_items', to='catalog.option', verbose_name='Форма')),
                ('topping', models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'topping'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping_items', to='catalog.option', verbose_name='Топпинг')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderItemBerry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена ягоды при покупке')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berry_links', to='orders.orderitem', verbose_name='Позиция')),
                ('option', models.ForeignKey(limit_choices_to={'category__slug': 'berries'}, on_delete=django.db.models.deletion.PROTECT, related_name='as_berry', to='catalog.option', verbose_name='Опция (ягода)')),
            ],
            options={
                'verbose_name': 'Ягода в позиции',
                'verbose_name_plural': 'Ягоды в позиции',
                'unique_together': {('item', 'option')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='berries',
            field=models.ManyToManyField(blank=True, related_name='berry_items', through='orders.OrderItemBerry', to='catalog.option', verbose_name='Ягоды'),
        ),
        migrations.CreateModel(
            name='OrderItemDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена декора при покупке')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_links', to='orders.orderitem', verbose_name='Позиция')),
                ('option', models.ForeignKey(limit_choices_to={'category__slug': 'decor'}, on_delete=django.db.models.deletion.PROTECT, related_name='as_decor', to='catalog.option', verbose_name='Опция (декор)')),
            ],
            options={
                'verbose_name': 'Декор в позиции',
                'verbose_name_plural': 'Декор в позиции',
                'unique_together': {('item', 'option')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='decors',
            field=models.ManyToManyField(blank=True, related_name='decor_items', through='orders.OrderItemDecor', to='catalog.option', verbose_name='Декор'),
        ),
    ]
