# Generated by Django 5.2.5 on 2025-08-27 19:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_cake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='inscription_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8, verbose_name='Цена надписи, ₽'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='inscription_text',
            field=models.CharField(blank=True, help_text='Мы можем разместить на торте любую надпись, например: «С днём рождения!»', max_length=64, verbose_name='Надпись (необязательно)'),
        ),
    ]
