# Generated by Django 5.2.5 on 2025-08-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cake_cakeimage'),
        ('orders', '0004_alter_orderitem_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='berries',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='decors',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='berry',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'berries'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='berry_item', to='catalog.option', verbose_name='Ягоды'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='decor',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__slug': 'decor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decor_item', to='catalog.option', verbose_name='Декор'),
        ),
    ]
