# Generated by Django 5.2.5 on 2025-08-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_berries_remove_orderitem_decors_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemdecor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitemdecor',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitemdecor',
            name='option',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('paid', 'Оплачен'), ('preparing', 'Готовится'), ('on_delivery', 'Доставляется'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='paid', max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='OrderItemBerry',
        ),
        migrations.DeleteModel(
            name='OrderItemDecor',
        ),
    ]
